# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='ImageToLabel',
  syntax='proto3',
  serialized_pb=_b('\n\ndata.proto\x12\x0cImageToLabel\"\x1b\n\x05Image\x12\x12\n\nimageBytes\x18\x01 \x01(\x0c\"\x16\n\x05Label\x12\r\n\x05label\x18\x01 \x01(\t2K\n\x0cImageToLabel\x12;\n\rGetImageLabel\x12\x13.ImageToLabel.Image\x1a\x13.ImageToLabel.Label\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='ImageToLabel.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageBytes', full_name='ImageToLabel.Image.imageBytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=55,
)


_LABEL = _descriptor.Descriptor(
  name='Label',
  full_name='ImageToLabel.Label',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='ImageToLabel.Label.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Label'] = _LABEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:ImageToLabel.Image)
  ))
_sym_db.RegisterMessage(Image)

Label = _reflection.GeneratedProtocolMessageType('Label', (_message.Message,), dict(
  DESCRIPTOR = _LABEL,
  __module__ = 'data_pb2'
  # @@protoc_insertion_point(class_scope:ImageToLabel.Label)
  ))
_sym_db.RegisterMessage(Label)



_IMAGETOLABEL = _descriptor.ServiceDescriptor(
  name='ImageToLabel',
  full_name='ImageToLabel.ImageToLabel',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=81,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetImageLabel',
    full_name='ImageToLabel.ImageToLabel.GetImageLabel',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_LABEL,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGETOLABEL)

DESCRIPTOR.services_by_name['ImageToLabel'] = _IMAGETOLABEL

# @@protoc_insertion_point(module_scope)
