# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import data_pb2 as data__pb2


class ImageToLabelStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetImageLabel = channel.unary_unary(
        '/imageToLabel.ImageToLabel/GetImageLabel',
        request_serializer=data__pb2.Image.SerializeToString,
        response_deserializer=data__pb2.Label.FromString,
        )


class ImageToLabelServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetImageLabel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageToLabelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetImageLabel': grpc.unary_unary_rpc_method_handler(
          servicer.GetImageLabel,
          request_deserializer=data__pb2.Image.FromString,
          response_serializer=data__pb2.Label.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'imageToLabel.ImageToLabel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
